### ISSUE TITLE
VS 2022 - Kubernetes publish not working - asp.net core 6

### ISSUE THREAD

**Issue by myappfree** [GoogleCloudPlatform/google-cloud-visualstudio#1121]
Publishing [ProjectNameHere] to Kubernetes.
Failed to deploy project [ProjectNameHere] to Kubernetes.

evenr the generate app.yaml fails

   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at GoogleCloudExtension.Services.Configuration.AppEngineConfiguration.CheckProjectConfiguration(IParsedProject project)
   at GoogleCloudExtension.GenerateConfigurationCommand.GenerateConfigurationContextMenuCommand.<GenerateConfigurationAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GoogleCloudExtension.Utils.ErrorHandlerUtils.<HandleExceptionsAsync>d__2.MoveNext()

**Comment by myappfree** [comment]
@jskeet any chance to fix the iussue
Thanks


Here my Workaround

first of all you need to install docker desktop

right click on project -> Add -> Docker Supoport

righ click on project-> open in Terminal

you need first time authentication

```
gcloud auth login
gcloud container clusters get-credentials {your cluster} --region {region} --project {project} gcloud auth configure-docker
```

create a script ps1
```

 $version = [DateTimeOffset]::Now.ToUnixTimeSeconds()

 docker build -t gcr.io/{project}/{your deployment name}:$version .

 docker push gcr.io/{project}/{your deployment name}:$version

 $deployment_yaml = (Get-Content .\Conf\Prod\deployment.yaml) -replace "{{version}}", $version

 $deployment_yaml | kubectl apply -f -

```
here an example of deployment.yaml please note the I have added {version} placeholder
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {your deployment name}
spec:
  replicas: 2
  selector:
    matchLabels:
      run: {your deployment name}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: {your deployment name}
    spec:
      containers:
      - image: gcr.io/{project}/{your deployment name}:{{version}}
        imagePullPolicy: IfNotPresent
        name: {your deployment name}
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 2Gi
```
